### PR TITLE
Use vercel/ncc

### PR DESCRIPTION
**Pull request by Purushothaman22**

### CODE REVIEW

**Comment by gps** [comment]
@Purushothaman22 I see node_modules has been removed. However, I don't see `dist/index.js` anywhere, or how to create it?

**Comment by Purushothaman22** [comment]
> @Purushothaman22 I see node_modules has been removed. However, I don't see `dist/index.js` anywhere, or how to create it?

`dist`  folder was added in gitignore. I'm pushing the `dist/Index.js` file now

**Comment by gps** [comment]
@Purushothaman22 how do we test this?

**Comment by Purushothaman22** [comment]
> @Purushothaman22 how do we test this?

I'm trying to test this in another project by creating a test branch

**Comment by Purushothaman22** [comment]
@gps  I've tested this. It's working fine.

**Pull request merged**
